docs(common): add contributing information
TalkControl/talk-control-revealjs-extensions pull request #23
Opened 2024-09-17 15:24 UTC by kuroidoruido

2024-09-20 07:27 UTC, jefBinomed requested changes

2024-09-20 07:27 UTC, jefBinomed commented on CODE_OF_CONDUCT.md
> +Communication through any of TalkControl's channels (GitHub, Gitter, IRC, mailing lists, Google+, Twitter, etc.) must be constructive and never resort to personal attacks, trolling, public or private
Ici, j'enlèverais la partie IRC/Google+, ça fait un peu oldschool :D. Je mettrais à la limite Discord en remplacement

2024-09-20 07:27 UTC, jefBinomed commented on CONTRIBUTING.md
> +2. run `npm ci`
On a pas cette commande, du coup, je pense qu'il faut l'enlever

2024-09-20 07:27 UTC, jefBinomed commented on README.md
> +    <a href="https://laravel.com" target="_blank"><img src="https://raw.githubusercontent.com/TalkControl/talk-control-revealjs-extensions/c81a3bb79852b61382e2a97444f5088d6102b3ec/public/talk-control
c'est fait exprès que ça pointe vers laravel :p ? L'image, on pourrait pas sinon la faire pointer vers le repo ? en path référentiel ?

2024-11-28 15:11 UTC, kuroidoruido commented on CONTRIBUTING.md
> +2. run `npm ci`
comment ça on a pas npm ci ?

2024-11-28 15:11 UTC, kuroidoruido commented on CODE_OF_CONDUCT.md
> +Communication through any of TalkControl's channels (GitHub, Gitter, IRC, mailing lists, Google+, Twitter, etc.) must be constructive and never resort to personal attacks, trolling, public or private
Je vais juste virer, mais ça veut dire qu'on a ça sur toutes les schools

2024-11-28 15:12 UTC, kuroidoruido commented on README.md
> +    <a href="https://laravel.com" target="_blank"><img src="https://raw.githubusercontent.com/TalkControl/talk-control-revealjs-extensions/c81a3bb79852b61382e2a97444f5088d6102b3ec/public/talk-control
je corrige

2024-11-29 15:02 UTC, jefBinomed commented on CONTRIBUTING.md
> +2. run `npm ci`
je vais retourner me coucher et enlever mon commentaire :D

2024-11-29 15:03 UTC, jefBinomed approved these changes

2024-11-29 15:07 UTC, merged